# 6) Remove Package
#--- Start ---#
---
- name: Remove Package
  hosts: localhost
  become: true
  vars:
    pack: xinetd
  tasks:
  - name: "Remove {{ pack }}"
    package:
      name: "{{ pack }}"
      state: absent
...
#--- End ---#
