# 7) Start Service
#--- Start ---#
---
- name: Start Service
  hosts: localhost
  become: true
  tasks:
  - name: Start xinetd
    service:
      name: xinetd
      state: started
      enabled: true
...
#--- End ---#
