# 9) Install Package
#--- Start ---#
---
- name: Install Package
  hosts: localhost
  become: true
  tasks:
  - name: Install httpd
    package:
      name: httpd
      state: latest
...
#--- End ---#
