# 8) Stop Service
#--- Start ---#
---
- name: Stop Service
  hosts: localhost
  become: true
  tasks:
  - name: Start httpd
    service:
      name: httpd
      state: started
      enabled: false
...
#--- End ---#
